### PR TITLE
About Page

### PR DESCRIPTION
**Pull request by Jinb2**
Cleaner version of #11

### CODE REVIEW

**Comment by Jinb2** [comment]
This is the hero section:
image

our mission and vision container:
image

our-staff container before:
image

our-staff container after: 
image
image

**Comment by jchen42703** [comment]
Pretty good job, but I had to refactor a bunch. Take a quick scan through the changes that made.

## Design
* The OUR STAFF should be moved inside of the $dark-green container
* I think it's cool that you made it so that you can make the pastor descriptions pop up with a click, but UI-wise, it's not clear that you're supposed to click on the pastor faces. Imo just make it single column with pastor faces + description

## Coding
* It would be nice if you did your paddings/margins with % instead of pixels, but it's okay.
  * If you have white spaces between containers, a lot of times that's the margin causing it. If you want to preserve the bg color, then use padding instead.
* Try to make font sizes consistent across the website.
  * I.e. use the variables in `_fontFormatting.scss`

Lmk if any of this is confusing. @Jinb2

**Comment by Jinb2** [comment]
our-staff-container:
image
image

**Comment by jchen42703** [comment]
Make the images with the circle overlay. That shit looked good

**Review by jchen42703 — APPROVED** [review]
Good enough. It will be refactored on #27 .

**Pull request merged**
